### ISSUE TITLE
Error: Fail to retrieve files src/variableGroups/lz-dev.yaml: Bad credentials

### ISSUE THREAD

**Issue by rokeno** [lindluni/actions-variable-groups#5]
I am trying to use this action in an Enterrise environment as a local action (company does not allow me to pull from non-verified creators.
I am getting 
```
Error: Fail to retrieve files src/variableGroups/lz-dev.yaml: Bad credentials
```
when i try to run this.
My env is:
- private runner accesing the repo and running the code.
- create variables to use further on

I used a token generated by me, i'm owner on the repo, but it did not work.

**Comment by lindluni** [comment]
Hi @rokeno 

Did you set the `url` property to point your instances API?

https://github.com/lindluni/actions-variable-groups/blob/main/action.yml#L15

**Comment by rokeno** [comment]
No, i did not.
I did after i posted the issue and i got:
```
Error: Fail to retrieve files src/variableGroups/lz-dev.yml: Not Found
```
...which tells me that it reached the repo, but it did not find the file.
Trying now to add  `${{ github.workspace }}/src/variableGroups/lz-dev.yml` to see the result

**Comment by lindluni** [comment]
You shouldn't include the workspace, it is using the contents endpoint to reach your repo file and not bringing the repo locally. Can you share a redacted copy of your the workflow step where you are using the Action?

I profess I've never tested this on GHES, I've only ever added the support. Deploying GHES myself now to test this out.

**Comment by lindluni** [comment]
Also, what scope did you give to your token?

**Comment by rokeno** [comment]
> Also, what scope did you give to your token?

Full.

**Comment by rokeno** [comment]
> 've never tested this on GHES, I've only ever added the support. Deploying GHES myself now to test this out.
```
      - name: Inject variables
        uses: ./.github/actions/actions-variable-groups-main
        with:
          org: ORG
          repo: PLATFORM
          url: https://github.domain.com/api/v3
          token: ${{ secrets.AUTHENTICATION_TOKEN }}
          groups: |
            src/variableGroups/lz-dev.yml
```
