### ISSUE TITLE
Can't find variable yml file in > 2.1.0

### ISSUE THREAD

**Issue by joshjohanning** [lindluni/actions-variable-groups#6]
I have a repo (`myrepo`) that runs a workflow. The repo also has a `export.yml` file in the root. I'm unable to get the action to pick up that file:

v1 works:
![image](https://user-images.githubusercontent.com/19912012/196513672-28eb652c-a1eb-4876-891b-5983c5c329cb.png)

v2 does not work:
![image](https://user-images.githubusercontent.com/19912012/196514181-e9ec3543-c069-4994-b2c9-d6bca775f173.png)

In my tests, it looks like it broke between [2.0.0..2.1.0](https://github.com/lindluni/actions-variable-groups/compare/v2.0.0...v2.1.0).

I tried not putting it a different folder other than the `.github` folder and it still fails, and trying to use a PAT even though it's in the same repo as the workflow is running.

```yml
      - name: Inject Variables
        uses: lindluni/actions-variable-groups@v2
        with:
          org: ${{ github.REPOSITORY_OWNER }}
          repo: ${{ github.event.repository.name }}
          token: ${{ secrets.MY_PAT }}
          groups: |
            export.yml
```
